# Generated by Django 4.2.20 on 2026-06-11 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='supervision', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='学生')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('enrollment_year', models.CharField(blank=True, max_length=4, verbose_name='入学年份')),
                ('college', models.CharField(max_length=100, verbose_name='学院')),
                ('class_number', models.CharField(blank=True, max_length=50, verbose_name='班级')),
                ('course_name', models.CharField(default='专业实习', max_length=100, verbose_name='课程名称')),
                ('course_code', models.CharField(default='CSE450', max_length=20, verbose_name='课程代码')),
                ('credits', models.CharField(default='4（4）', max_length=20, verbose_name='学分')),
                ('internship_type', models.CharField(default='专业实习', max_length=50, verbose_name='实习类型')),
                ('internship_org_form', models.CharField(default='集中实习', max_length=50, verbose_name='组织形式')),
                ('internship_method', models.CharField(default='现场实习', max_length=50, verbose_name='实习方式')),
                ('academic_year', models.CharField(default='2024-2025学年', max_length=50, verbose_name='学年')),
                ('is_school_base', models.CharField(default='否', max_length=10, verbose_name='是否校内基地')),
                ('is_digital_base', models.CharField(default='否', max_length=10, verbose_name='是否数字化基地')),
                ('is_overseas_base', models.CharField(default='否', max_length=10, verbose_name='是否境外基地')),
                ('company', models.CharField(max_length=100, verbose_name='实习单位')),
                ('company_credit_code', models.CharField(blank=True, max_length=50, verbose_name='统一社会信用代码')),
                ('internship_area_code', models.CharField(blank=True, max_length=20, verbose_name='实习地区代码')),
                ('internship_address', models.CharField(max_length=200, verbose_name='实习详细地址')),
                ('has_liability_insurance', models.CharField(default='是', max_length=10, verbose_name='是否有责任保险')),
                ('has_accident_insurance', models.CharField(default='是', max_length=10, verbose_name='是否有意外险')),
                ('has_safety_training', models.CharField(default='是', max_length=10, verbose_name='是否有安全培训')),
                ('has_tripartite_agreement', models.CharField(default='是', max_length=10, verbose_name='是否有三方协议')),
                ('company_acquisition_method', models.CharField(blank=True, max_length=50, verbose_name='单位获取方式')),
                ('has_emergency_plan', models.CharField(default='是', max_length=10, verbose_name='是否有应急预案')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('total_days', models.IntegerField(verbose_name='实习天数')),
                ('internship_position', models.CharField(blank=True, max_length=100, verbose_name='实习岗位')),
                ('internship_salary', models.CharField(blank=True, max_length=50, verbose_name='实习薪资')),
                ('company_supervisor', models.CharField(blank=True, max_length=50, verbose_name='企业导师')),
                ('teacher', models.CharField(blank=True, max_length=50, verbose_name='校内导师')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '实习监管信息',
                'verbose_name_plural': '实习监管信息',
                'db_table': 'supervisions',
                'ordering': ['-created_at'],
            },
        ),
    ]
