# Generated by Django 4.2.20 on 2026-06-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['order', '-created_at'], 'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='order',
            field=models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序'),
        ),
    ]
