# Generated by Django 4.2.20 on 2026-06-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='deadline',
            field=models.DateTimeField(verbose_name='截止时间'),
        ),
    ]
