# Generated by Django 4.2.20 on 2026-06-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_alter_batch_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=50, verbose_name='批次名称'),
        ),
    ]
