# Generated by Django 4.2.20 on 2026-06-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_alter_batch_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['created_at'], 'verbose_name': '批次', 'verbose_name_plural': '批次'},
        ),
    ]
