# Generated by Django 4.2.20 on 2026-06-11 11:55

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='学号')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别')),
                ('college', models.CharField(blank=True, max_length=100, verbose_name='学院')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='专业')),
                ('class_number', models.CharField(blank=True, max_length=50, verbose_name='班级')),
                ('batch', models.CharField(default='无', max_length=50, verbose_name='批次')),
                ('role', models.CharField(choices=[('student', '学生'), ('admin', '管理员')], default='student', max_length=20, verbose_name='角色')),
                ('is_profile_complete', models.BooleanField(default=False, verbose_name='资料是否完整')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
