# Generated by Django 4.2.20 on 2026-06-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['student_id'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
