# Generated by Django 4.2.20 on 2026-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['student_id'], 'verbose_name': '实习登记表', 'verbose_name_plural': '实习登记表'},
        ),
        migrations.AlterField(
            model_name='registration',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='total_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='实习天数'),
        ),
    ]
