# Generated by Django 4.2.20 on 2026-06-11 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='internship', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='学生')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('college', models.CharField(max_length=100, verbose_name='学院')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('teacher', models.CharField(max_length=50, verbose_name='指导教师')),
                ('company', models.CharField(max_length=100, verbose_name='实习单位')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('total_days', models.IntegerField(verbose_name='实习天数')),
                ('internship_content', models.TextField(blank=True, verbose_name='实习内容')),
                ('experience', models.TextField(blank=True, verbose_name='实习体会')),
                ('suggestions', models.TextField(blank=True, verbose_name='建议')),
                ('submit_date', models.DateTimeField(auto_now_add=True, verbose_name='提交日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '实习报告',
                'verbose_name_plural': '实习报告',
                'db_table': 'internships',
                'ordering': ['-submit_date'],
            },
        ),
    ]
